version: '3'
services:
  ml2:
    restart: always
    container_name: ml2
    image: pragusga/eews:ml-v1
    environment:
      - REDIS_HOST=<redis-host>
      - REDIS_PORT=<redis-port>
      - REDIS_PASSWORD=<redis-pass>
    ports:
      - '3002:3000'
    mem_limit: 7g
  ml3:
    restart: always
    container_name: ml3
    image: pragusga/eews:ml-v1
    environment:
      - REDIS_HOST=<redis-host>
      - REDIS_PORT=<redis-port>
      - REDIS_PASSWORD=<redis-pass>
    ports:
      - '3003:3000'
    mem_limit: 7g
