version: '3'
services:
  ml1:
    restart: always
    container_name: ml1
    image: pragusga/eews:ml-v1
    environment:
      - REDIS_HOST=<redis-host>
      - REDIS_PORT=<redis-port>
    ports:
      - '3001:3000'
